Repository citation-dev/citation, pull requests merged in 2022-08, with the labels that each got.

#10 chore: improve Dockerfile
  Dockerfile
Labels: ✨improvement

#15 feat: デバックメッセージコマンドの追加
  docs/README.md
  docs/commands/details.md
  docs/commands/overview.md
  docs/commands/remove.md
  src/main/kotlin/dev/m2en/citation/Main.kt
  src/main/kotlin/dev/m2en/citation/command/DebugMessageCommand.kt
  src/main/kotlin/dev/m2en/citation/command/RegisterCommand.kt
Labels: ✨improvement

#16 Release v1.0.0
  .env.example
  README.md
  docs/README.md
  docs/commands/details.md
  docs/commands/overview.md
  docs/commands/remove.md
  docs/function/quote.md
  docs/getting-started.md
  src/main/kotlin/dev/m2en/citation/Main.kt
  src/main/kotlin/dev/m2en/citation/Quote.kt
  src/main/kotlin/dev/m2en/citation/command/DebugMessageCommand.kt
  src/main/kotlin/dev/m2en/citation/command/RegisterCommand.kt
Labels: ✨improvement, ✨enhancement, ✨documentation

#20 fix: Webhookの引用が行われない問題を修正
  src/main/kotlin/dev/m2en/citation/Quote.kt
Labels: 🐛bug

#21 feat: Embedのみのメッセージだった場合は引用しないように
  src/main/kotlin/dev/m2en/citation/Quote.kt
Labels: ✨improvement

#22 Release v1.0.1
  .github/workflows/build.yml
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  src/main/kotlin/dev/m2en/citation/Quote.kt
Labels: 🐛bug, ✨improvement, 🔮workflow (gh-actions)

#25 feat: 引用の削除機能を追加
  src/main/kotlin/dev/m2en/citation/Main.kt
  src/main/kotlin/dev/m2en/citation/QuoteDelete.kt
  src/main/kotlin/dev/m2en/citation/QuoteSend.kt
  src/main/kotlin/dev/m2en/citation/command/HelpCommand.kt
  src/main/kotlin/dev/m2en/citation/command/MessageCommandInterface.kt
  src/main/kotlin/dev/m2en/citation/command/RegisterCommand.kt
Labels: ✨enhancement

#24 Release v1.1.0
  README.md
  build.gradle.kts
  docs/commands/details.md
  docs/function/debug.md
  docs/function/quote.md
  docs/images/004327.png
  docs/images/215021.png
  src/main/kotlin/dev/m2en/citation/Main.kt
  src/main/kotlin/dev/m2en/citation/QuoteDelete.kt
  src/main/kotlin/dev/m2en/citation/QuoteSend.kt
  src/main/kotlin/dev/m2en/citation/command/DebugCommand.kt
  src/main/kotlin/dev/m2en/citation/command/MessageCommandInterface.kt
  src/main/kotlin/dev/m2en/citation/command/RegisterCommand.kt
  src/main/kotlin/dev/m2en/citation/command/chat/HelpCommand.kt
  src/main/kotlin/dev/m2en/citation/command/message/DebugCommand.kt
  src/main/kotlin/dev/m2en/citation/command/message/RegisterCommand.kt
Labels: 🐛bug, ✨enhancement, ✨documentation
